# Generated by Django 5.0.2 on 2024-04-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('videos', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
