# Generated by Django 5.0.2 on 2024-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom_app', '0003_subject_alter_classes_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
