# Generated by Django 5.0.2 on 2024-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom_app', '0004_classes_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
