# Generated by Django 5.0.4 on 2024-04-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom_app', '0005_delete_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('videos', models.FileField(upload_to='videos')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clsroom_app.subject')),
            ],
        ),
    ]
